#!/usr/bin/env python3
"""
Check which response files contain valid data.
A valid response is:
- Non-empty file (size > 0)
- Contains valid JSON
- Has meaningful content (not just {})
"""

import json
import os
from pathlib import Path

def is_valid_response(filepath):
    """Check if a response file contains valid data."""
    try:
        # Check if file exists and has size
        if not os.path.exists(filepath):
            return False, "File does not exist"
        
        file_size = os.path.getsize(filepath)
        if file_size == 0:
            return False, "Empty file"
        
        # Try to parse as JSON
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Check if it's just an empty dict or list
        if data == {} or data == []:
            return False, "Empty JSON object"
        
        # Check for common error indicators
        if isinstance(data, dict):
            # Check for error messages
            if 'error' in data:
                return False, f"API Error: {data.get('error', {}).get('message', 'Unknown error')}"
            
            # Check for authentication errors
            if 'message' in data and any(word in str(data['message']).lower() for word in ['unauthorized', 'forbidden', 'invalid', 'authentication']):
                return False, f"Auth Error: {data['message']}"
        
        # If we got here, it's likely valid data
        return True, f"Valid (size: {file_size} bytes)"
        
    except json.JSONDecodeError as e:
        return False, f"Invalid JSON: {str(e)}"
    except Exception as e:
        return False, f"Error: {str(e)}"


def main():
    """Scan all response files and report validity."""
    responses_dir = Path('/Users/ron.s/dev/sick-rats/responses')
    
    valid_files = []
    invalid_files = []
    
    # Walk through all subdirectories
    for extension_dir in sorted(responses_dir.iterdir()):
        if not extension_dir.is_dir():
            continue
        
        for response_file in sorted(extension_dir.glob('*.json')):
            relative_path = response_file.relative_to(responses_dir)
            full_path = str(response_file)
            
            is_valid, reason = is_valid_response(full_path)
            
            if is_valid:
                valid_files.append({
                    'path': str(relative_path),
                    'full_path': full_path,
                    'reason': reason
                })
            else:
                invalid_files.append({
                    'path': str(relative_path),
                    'full_path': full_path,
                    'reason': reason
                })
    
    # Generate report
    print("=" * 70)
    print("🔍 RESPONSE FILE VALIDATION REPORT")
    print("=" * 70)
    print()
    print(f"📊 SUMMARY:")
    print(f"   Total files scanned: {len(valid_files) + len(invalid_files)}")
    print(f"   ✅ Valid responses: {len(valid_files)}")
    print(f"   ❌ Invalid/Empty responses: {len(invalid_files)}")
    print()
    
    # Write valid responses to file
    with open('/Users/ron.s/dev/sick-rats/valid_responses.txt', 'w') as f:
        f.write("# Valid API Response Files\n")
        f.write("# Generated by check_valid_responses.py\n")
        f.write(f"# Total valid responses: {len(valid_files)}\n")
        f.write("\n")
        
        if valid_files:
            f.write("# Valid Responses:\n")
            for item in valid_files:
                f.write(f"{item['full_path']}\n")
        else:
            f.write("# No valid responses found\n")
        
        f.write("\n# Invalid/Empty Responses:\n")
        for item in invalid_files:
            f.write(f"# {item['path']}: {item['reason']}\n")
    
    print("✅ VALID RESPONSES:")
    print("-" * 70)
    if valid_files:
        for item in valid_files:
            print(f"   ✅ {item['path']}")
            print(f"      {item['reason']}")
    else:
        print("   (No valid responses found - files are empty or not yet populated)")
    
    print()
    print("❌ INVALID/EMPTY RESPONSES:")
    print("-" * 70)
    for item in invalid_files[:10]:  # Show first 10
        print(f"   ❌ {item['path']}")
        print(f"      {item['reason']}")
    
    if len(invalid_files) > 10:
        print(f"   ... and {len(invalid_files) - 10} more")
    
    print()
    print("=" * 70)
    print(f"📝 Valid response paths written to: valid_responses.txt")
    print("=" * 70)

if __name__ == '__main__':
    main()
